name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project with Maven Wrapper
        run: ./mvnw package -DskipTests

      - name: Prepare app.jar for Docker
        run: cp target/*.jar app.jar

      - name: Create deployment package (ZIP)
        run: zip -r deploy.zip Dockerfile app.jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get AWS Account ID
        id: aws-account
        run: echo "account_id=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_OUTPUT

      - name: Upload ZIP to S3
        run: |
          aws s3 cp deploy.zip s3://elasticbeanstalk-${{ secrets.AWS_REGION }}-${{ steps.aws-account.outputs.account_id }}/tene-api/deploy-${{ github.sha }}-${{ github.run_number }}.zip

      - name: Create EB application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name tene-api \
            --version-label deploy-${{ github.sha }}-${{ github.run_number }} \
            --source-bundle S3Bucket=elasticbeanstalk-${{ secrets.AWS_REGION }}-${{ steps.aws-account.outputs.account_id }},S3Key=tene-api/deploy-${{ github.sha }}-${{ github.run_number }}.zip \
            --process

      - name: Wait for AWS to register version
        run: sleep 40

      - name: Update Elastic Beanstalk environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name tene-api-docker-env \
            --version-label deploy-${{ github.sha }}-${{ github.run_number }}
