name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project with Maven Wrapper
        run: ./mvnw package -DskipTests

      - name: Prepare app.jar for Docker
        run: cp target/*.jar app.jar

      - name: Create deployment package (ZIP)
        run: zip -r deploy.zip Dockerfile app.jar

      - name: Upload to Elastic Beanstalk (create version only)
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: tene-api
          environment_name: tene-api-docker-env
          version_label: deploy-${{ github.sha }}-${{ github.run_number }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
          wait_for_deployment: false
          use_existing_version_if_available: true

      - name: Wait for EB version to register
        run: sleep 20

      - name: Deploy application version
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: tene-api
          environment_name: tene-api-docker-env
          version_label: deploy-${{ github.sha }}-${{ github.run_number }}
          region: ${{ secrets.AWS_REGION }}
          wait_for_deployment: true
          use_existing_version_if_available: true
