name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # lub 'master' jeśli używasz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_REGISTRY_PASSWORD }}" | docker login ${{ secrets.AZURE_REGISTRY }} \
            --username ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY }}/tene-api:latest .

      - name: Push image to ACR
        run: |
          docker push ${{ secrets.AZURE_REGISTRY }}/tene-api:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ secrets.AZURE_REGISTRY }}/tene-api:latest
